# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configcures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.box = "generic/alpine312"

  config.vm.provider "virtualbox" do |hv|
    hv.cpus = "1"
    hv.memory = "2048"
  end

  config.vm.network :forwarded_port, guest: 8080, host: 42422

  config.vm.synced_folder 'src', '/vagrant'

  config.ssh.password = "vagrant"


  config.vm.define "ppoinsinS" do |host1|
    host1.vm.hostname = "ppoinsinS"
    host1.vm.network "private_network", ip: "192.168.56.110"

    host1.vm.provision "install-docker", type: "shell", inline:<<-SHELL
    apk add --update docker openrc 
    service docker start
    rc-update add docker boot
    SHELL

    host1.vm.provision "install-k3d", after: "install-docker", type: "shell", inline:<<-SHELL
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"

    chmod +x ./kubectl

    sudo mv ./kubectl /usr/local/bin/kubectl

    curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash

    SHELL

    host1.vm.provision "install-argocd", after: "install-k3d", type: "shell", inline:<<-SHELL

    # resource : https://tanzu.vmware.com/developer/guides/argocd-gs/

    sh /vagrant/install.sh

    # Creating app

    # kubectl port-forward svc/argocd-server -n argocd 8080:443 --address='0.0.0.0'

    SHELL
    
  end



  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
